apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snakes-and-ladders
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: snakes-and-ladders
    newName: rg.fr-par.scw.cloud/djnd/snakes-and-ladders
    newTag: 'fcb4007643444f7f9ecf9021f8e9ef45bf49a626'
